### ISSUE TITLE
Dimmension added to the qc files

### ISSUE THREAD

**Issue by Gehova** [jrl-umi3218/sch-creator#3]
Hello

There is a little discrepancy between the files generated by the scripts and the expected file in sch-creator.
The script "export_qc.py" writes the dimension and number of points in the file:

file.write('3\n')
file.write('%s\n' % len(cloud))

but the function "SmoothHullGeneratorVVR::readVertex" only reads the number of points in the file, so that extra number causes errors.  I don't know if I'm calling the program wrong or something, because you also had tests in 2D in your paper, so that will explain why the program needs to know the dimension.

**Comment by jorisv** [comment]
Hello

I think this issue can be related to this [pull request](https://github.com/jrl-umi3218/sch-creator/pull/1).
I will see if someone can merge it.

Meanwhile you can use this forked [repository](https://github.com/jorisv/sch-creator) that's compatible with the blender script output (have the same input than qhull).

**Comment by jorisv** [comment]
The pull request has been merged.
If that solve your problem I will close this issue.

**Comment by Gehova** [comment]
Hello.
Yes, the function readvertex in the forked  repository solves the issue.
